- type: job
  id: ResearchDirector
  name: job-name-rd
  description: job-description-rd
  color: "#D381C9"
  playTimeTracker: JobResearchDirector
  requirements:
    - !type:RoleTimeRequirement
      role: JobSeniorResearcher
      time: 43200 #12 hrs
    - !type:OverallPlaytimeRequirement
      time: 144000 #40 hrs
  weight: 10
  startingGear: ResearchDirectorGear
  icon: "JobIconResearchDirector"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  access:
  - Research
  - Command
  - Maintenance
  - ResearchDirector
  - Brig
  - Cryogenics
  - Robotics
  special:
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: ResearchDirectorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitResearchDirector
    back: ClothingBackpackResearchDirectorFilled
    shoes: ClothingShoesColorBrown
    outerClothing: ClothingOuterCoatRD
    id: RnDPDA
    ears: ClothingHeadsetRD
    eyes: ClothingEyesHUDGlassesScience
  innerClothingSkirt: ClothingUniformJumpskirtResearchDirector
  satchel: ClothingBackpackSatchelResearchDirectorFilled
  duffelbag: ClothingBackpackDuffelResearchDirectorFilled
